extension["终末祷铸"]={
	intro:"三扩(差异教徒)，本体最低版本1.0.20，反馈QQ群966951007",
	date:'2025/04/04',
	author:"农杰",
	netdisk:"",
	forum:"",
	version:"3.0",
	files:["info.json","README.md","LICENSE","character/hongYiZhuJiao.jpg",
	"character/tieLvZhe.jpg","zhuanShu/wangQuanBaoZhu.png",'zhuanShu/shiShuCard.png','character/jiLuZhe.jpg','zhuanShu/luBiao.png','character/chuanJiaoShi.jpg'],
	size:"1.56MB",
};