extension["终末祷铸"]={
	intro:"三扩(目前阿斯兰)，本体最低版本1.0.18",
	author:"农杰",
	netdisk:"",
	forum:"",
	version:"1.0",
	files:["info.json","README.md","LICENSE","character/hongYiZhuJiao.jpg",
	"character/tieLvZhe.jpg","zhuanShu/wangQuanBaoZhu.png"],
	size:"976KB"
};