if (!localStorage.getItem('old-extension-tip')) {
	alert('您在游戏内的扩展栏目获取的扩展可能导致游戏崩溃' +
		'，请谨慎下载');
	localStorage.setItem('old-extension-tip', 'true');
};

extension["织梦者"] = {
	date: "2025/05/12",
	intro: "玩弄技能的角色。游戏本体版本最低v1.0.2",
	author: "农之",
	netdisk: "",
	forum: "",
	version: "1.5",
	files: ["info.json", "LICENSE", "mengJingSuXing.jpg", "package.js", "README.md", "zhiMengZhe.jpg"],
	size: "1.8MB"
};

extension["创世纪"] = {
	date: "2026/08/25",
	intro: "添加角色贝亚娜斗神、百花缭乱、露米娅、天启者、狱血魔神。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "2.2",
	files: ["info.json", "README.md", "LICENSE", "package.js", "beiyanadopushen.png", "baiHuaLiaoLuan.png", "luMiYa.png", "tianQiZhe.png", "yuXueMoShen.png", "mark_nianQi.png", "mark_luMiYaYanJiu.png", "mark_shenPan.png", "mark_rongYuZhuFu.png", "mark_shouHuHuiZhang.png", "mark_wuQiZhuFu.png", "mark_tianShiZhuFu.png", "mark_xueQi.png", "mark_xueShaXingTai.png"],
	size: "10.21MB"
};

extension["十周年-AI优化版"] = {
	date: "2026/08/23",
	intro: "独立的十周年角色AI优化补丁，不修改原版技能设计。",
	author: "蒙牛 / Codex",
	netdisk: "",
	forum: "",
	version: "1.5",
	files: ["info.json", "README.md", "package.js"],
	size: "427KB"
};

extension["十周年-噩梦人机"] = {
	date: "2026/08/23",
	intro: "继承十周年-AI优化版，为70名电脑角色添加140项噩梦强化；支持原版、高清与Q版三档头像，并允许联机玩家独立选择。",
	author: "蒙牛 / Codex",
	netdisk: "",
	forum: "",
	version: "1.1",
	files: [
		"info.json",
		"README.md",
		"package.js",
		"image/character/default/anShaZhe.png",
		"image/character/default/cangYanMoNv.png",
		"image/character/default/dieWuZhe.png",
		"image/character/default/fengYinShi.png",
		"image/character/default/fengZhiJianSheng.png",
		"image/character/default/geDouJia.png",
		"image/character/default/hongLianQiShi.png",
		"image/character/default/jianDi.png",
		"image/character/default/jingLingSheShou.png",
		"image/character/default/kuangZhanShi.png",
		"image/character/default/lingFuShi.png",
		"image/character/default/lingHunShuShi.png",
		"image/character/default/maoXianJia.png",
		"image/character/default/moFaShaoNv.png",
		"image/character/default/moGong.png",
		"image/character/default/moJianShi.png",
		"image/character/default/moQiang.png",
		"image/character/default/nvWuShen.png",
		"image/character/default/qiDaoShi.png",
		"image/character/default/shengGong.png",
		"image/character/default/shengNv.png",
		"image/character/default/shengQiangQiShi.png",
		"image/character/default/shenGuan.png",
		"image/character/default/shenJianShou.png",
		"image/character/default/shouLingWuShi.png",
		"image/character/default/tianShi.png",
		"image/character/default/wenYiFaShi.png",
		"image/character/default/xianZhe.png",
		"image/character/default/xueSeJianLing.png",
		"image/character/default/xueZhiWuNv.png",
		"image/character/default/yingLingRenXing.png",
		"image/character/default/yinYangShi.png",
		"image/character/default/yinYouShiRen.png",
		"image/character/default/yongZhe.png",
		"image/character/default/yuanSuShi.png",
		"image/character/default/yueZhiNvShen.png",
		"image/character/default/zhongCaiZhe.png",
		"image/character/nightmare/anShaZhe.png",
		"image/character/nightmare/cangYanMoNv.png",
		"image/character/nightmare/dieWuZhe.png",
		"image/character/nightmare/fengYinShi.png",
		"image/character/nightmare/fengZhiJianSheng.png",
		"image/character/nightmare/geDouJia.png",
		"image/character/nightmare/hongLianQiShi.png",
		"image/character/nightmare/jianDi.png",
		"image/character/nightmare/jingLingSheShou.png",
		"image/character/nightmare/kuangZhanShi.png",
		"image/character/nightmare/lingFuShi.png",
		"image/character/nightmare/lingHunShuShi.png",
		"image/character/nightmare/maoXianJia.png",
		"image/character/nightmare/moFaShaoNv.png",
		"image/character/nightmare/moGong.png",
		"image/character/nightmare/moJianShi.png",
		"image/character/nightmare/moQiang.png",
		"image/character/nightmare/nvWuShen.png",
		"image/character/nightmare/qiDaoShi.png",
		"image/character/nightmare/shengGong.png",
		"image/character/nightmare/shengNv.png",
		"image/character/nightmare/shengQiangQiShi.png",
		"image/character/nightmare/shenGuan.png",
		"image/character/nightmare/shenJianShou.png",
		"image/character/nightmare/shouLingWuShi.png",
		"image/character/nightmare/tianShi.png",
		"image/character/nightmare/wenYiFaShi.png",
		"image/character/nightmare/xianZhe.png",
		"image/character/nightmare/xueSeJianLing.png",
		"image/character/nightmare/xueZhiWuNv.png",
		"image/character/nightmare/yingLingRenXing.png",
		"image/character/nightmare/yinYangShi.png",
		"image/character/nightmare/yinYouShiRen.png",
		"image/character/nightmare/yongZhe.png",
		"image/character/nightmare/yuanSuShi.png",
		"image/character/nightmare/yueZhiNvShen.png",
		"image/character/nightmare/zhongCaiZhe.png",
		"image/character/default/shengDianQiShi.png",
		"image/character/default/shengTingJianChaShi.png",
		"image/character/default/yuanChuZhiGong.png",
		"image/character/default/xingZhuiNvWu.png",
		"image/character/default/zhanDouFaShi.png",
		"image/character/default/lieWuRen.png",
		"image/character/default/nvPuZhang.png",
		"image/character/default/jinGuiZhiNv.png",
		"image/character/default/shiShenZhe.png",
		"image/character/default/ranWuZhe.png",
		"image/character/default/jieJieShi.png",
		"image/character/default/shenMiXueZhe.png",
		"image/character/default/hongYiZhuJiao.png",
		"image/character/default/zhuLvZhe.png",
		"image/character/default/jiLuZhe.png",
		"image/character/default/chuanJiaoShi.png",
		"image/character/default/yiJiaoTu.png",
		"image/character/default/nong_baoShiShaoNv.png",
		"image/character/default/youJiShi.png",
		"image/character/default/jianZhiMoNv.png",
		"image/character/default/jieRiMoDao.png",
		"image/character/default/luoLiFanZhang.png",
		"image/character/default/tanLanShaoNv.png",
		"image/character/default/lingXiZhiChao.png",
		"image/character/default/jianXiZhiPian.png",
		"image/character/default/daoDanLuoLi.png",
		"image/character/default/yueTuanShouXi.png",
		"image/character/default/zhouFuShi.png",
		"image/character/default/sheng_zhongCaiZhe.png",
		"image/character/default/daiDuoShaoNv.png",
		"image/character/default/jiDuShaoNv.png",
		"image/character/default/jianZhiZi.png",
		"image/character/default/moGongEX.png",
		"image/character/nightmare/shengDianQiShi.png",
		"image/character/nightmare/shengTingJianChaShi.png",
		"image/character/nightmare/yuanChuZhiGong.png",
		"image/character/nightmare/xingZhuiNvWu.png",
		"image/character/nightmare/zhanDouFaShi.png",
		"image/character/nightmare/lieWuRen.png",
		"image/character/nightmare/nvPuZhang.png",
		"image/character/nightmare/jinGuiZhiNv.png",
		"image/character/nightmare/shiShenZhe.png",
		"image/character/nightmare/ranWuZhe.png",
		"image/character/nightmare/jieJieShi.png",
		"image/character/nightmare/shenMiXueZhe.png",
		"image/character/nightmare/hongYiZhuJiao.png",
		"image/character/nightmare/zhuLvZhe.png",
		"image/character/nightmare/jiLuZhe.png",
		"image/character/nightmare/chuanJiaoShi.png",
		"image/character/nightmare/yiJiaoTu.png",
		"image/character/nightmare/nong_baoShiShaoNv.png",
		"image/character/nightmare/youJiShi.png",
		"image/character/nightmare/jianZhiMoNv.png",
		"image/character/nightmare/jieRiMoDao.png",
		"image/character/nightmare/luoLiFanZhang.png",
		"image/character/nightmare/tanLanShaoNv.png",
		"image/character/nightmare/lingXiZhiChao.png",
		"image/character/nightmare/jianXiZhiPian.png",
		"image/character/nightmare/daoDanLuoLi.png",
		"image/character/nightmare/yueTuanShouXi.png",
		"image/character/nightmare/zhouFuShi.png",
		"image/character/nightmare/sheng_zhongCaiZhe.png",
		"image/character/nightmare/daiDuoShaoNv.png",
		"image/character/nightmare/jiDuShaoNv.png",
		"image/character/nightmare/jianZhiZi.png",
		"image/character/nightmare/moGongEX.png",
		"image/character/chibi/default/anShaZhe.png",
		"image/character/chibi/default/cangYanMoNv.png",
		"image/character/chibi/default/chuanJiaoShi.png",
		"image/character/chibi/default/daiDuoShaoNv.png",
		"image/character/chibi/default/daoDanLuoLi.png",
		"image/character/chibi/default/dieWuZhe.png",
		"image/character/chibi/default/fengYinShi.png",
		"image/character/chibi/default/fengZhiJianSheng.png",
		"image/character/chibi/default/geDouJia.png",
		"image/character/chibi/default/hongLianQiShi.png",
		"image/character/chibi/default/hongYiZhuJiao.png",
		"image/character/chibi/default/jiDuShaoNv.png",
		"image/character/chibi/default/jiLuZhe.png",
		"image/character/chibi/default/jianDi.png",
		"image/character/chibi/default/jianXiZhiPian.png",
		"image/character/chibi/default/jianZhiMoNv.png",
		"image/character/chibi/default/jianZhiZi.png",
		"image/character/chibi/default/jieJieShi.png",
		"image/character/chibi/default/jieRiMoDao.png",
		"image/character/chibi/default/jinGuiZhiNv.png",
		"image/character/chibi/default/jingLingSheShou.png",
		"image/character/chibi/default/kuangZhanShi.png",
		"image/character/chibi/default/lieWuRen.png",
		"image/character/chibi/default/lingFuShi.png",
		"image/character/chibi/default/lingHunShuShi.png",
		"image/character/chibi/default/lingXiZhiChao.png",
		"image/character/chibi/default/luoLiFanZhang.png",
		"image/character/chibi/default/maoXianJia.png",
		"image/character/chibi/default/moFaShaoNv.png",
		"image/character/chibi/default/moGong.png",
		"image/character/chibi/default/moGongEX.png",
		"image/character/chibi/default/moJianShi.png",
		"image/character/chibi/default/moQiang.png",
		"image/character/chibi/default/nong_baoShiShaoNv.png",
		"image/character/chibi/default/nvPuZhang.png",
		"image/character/chibi/default/nvWuShen.png",
		"image/character/chibi/default/qiDaoShi.png",
		"image/character/chibi/default/ranWuZhe.png",
		"image/character/chibi/default/shenGuan.png",
		"image/character/chibi/default/shenJianShou.png",
		"image/character/chibi/default/shenMiXueZhe.png",
		"image/character/chibi/default/shengDianQiShi.png",
		"image/character/chibi/default/shengGong.png",
		"image/character/chibi/default/shengNv.png",
		"image/character/chibi/default/shengQiangQiShi.png",
		"image/character/chibi/default/shengTingJianChaShi.png",
		"image/character/chibi/default/sheng_zhongCaiZhe.png",
		"image/character/chibi/default/shiShenZhe.png",
		"image/character/chibi/default/shouLingWuShi.png",
		"image/character/chibi/default/tanLanShaoNv.png",
		"image/character/chibi/default/tianShi.png",
		"image/character/chibi/default/wenYiFaShi.png",
		"image/character/chibi/default/xianZhe.png",
		"image/character/chibi/default/xingZhuiNvWu.png",
		"image/character/chibi/default/xueSeJianLing.png",
		"image/character/chibi/default/xueZhiWuNv.png",
		"image/character/chibi/default/yiJiaoTu.png",
		"image/character/chibi/default/yinYangShi.png",
		"image/character/chibi/default/yinYouShiRen.png",
		"image/character/chibi/default/yingLingRenXing.png",
		"image/character/chibi/default/yongZhe.png",
		"image/character/chibi/default/youJiShi.png",
		"image/character/chibi/default/yuanChuZhiGong.png",
		"image/character/chibi/default/yuanSuShi.png",
		"image/character/chibi/default/yueTuanShouXi.png",
		"image/character/chibi/default/yueZhiNvShen.png",
		"image/character/chibi/default/zhanDouFaShi.png",
		"image/character/chibi/default/zhongCaiZhe.png",
		"image/character/chibi/default/zhouFuShi.png",
		"image/character/chibi/default/zhuLvZhe.png",
		"image/character/chibi/nightmare/anShaZhe.png",
		"image/character/chibi/nightmare/cangYanMoNv.png",
		"image/character/chibi/nightmare/chuanJiaoShi.png",
		"image/character/chibi/nightmare/daiDuoShaoNv.png",
		"image/character/chibi/nightmare/daoDanLuoLi.png",
		"image/character/chibi/nightmare/dieWuZhe.png",
		"image/character/chibi/nightmare/fengYinShi.png",
		"image/character/chibi/nightmare/fengZhiJianSheng.png",
		"image/character/chibi/nightmare/geDouJia.png",
		"image/character/chibi/nightmare/hongLianQiShi.png",
		"image/character/chibi/nightmare/hongYiZhuJiao.png",
		"image/character/chibi/nightmare/jiDuShaoNv.png",
		"image/character/chibi/nightmare/jiLuZhe.png",
		"image/character/chibi/nightmare/jianDi.png",
		"image/character/chibi/nightmare/jianXiZhiPian.png",
		"image/character/chibi/nightmare/jianZhiMoNv.png",
		"image/character/chibi/nightmare/jianZhiZi.png",
		"image/character/chibi/nightmare/jieJieShi.png",
		"image/character/chibi/nightmare/jieRiMoDao.png",
		"image/character/chibi/nightmare/jinGuiZhiNv.png",
		"image/character/chibi/nightmare/jingLingSheShou.png",
		"image/character/chibi/nightmare/kuangZhanShi.png",
		"image/character/chibi/nightmare/lieWuRen.png",
		"image/character/chibi/nightmare/lingFuShi.png",
		"image/character/chibi/nightmare/lingHunShuShi.png",
		"image/character/chibi/nightmare/lingXiZhiChao.png",
		"image/character/chibi/nightmare/luoLiFanZhang.png",
		"image/character/chibi/nightmare/maoXianJia.png",
		"image/character/chibi/nightmare/moFaShaoNv.png",
		"image/character/chibi/nightmare/moGong.png",
		"image/character/chibi/nightmare/moGongEX.png",
		"image/character/chibi/nightmare/moJianShi.png",
		"image/character/chibi/nightmare/moQiang.png",
		"image/character/chibi/nightmare/nong_baoShiShaoNv.png",
		"image/character/chibi/nightmare/nvPuZhang.png",
		"image/character/chibi/nightmare/nvWuShen.png",
		"image/character/chibi/nightmare/qiDaoShi.png",
		"image/character/chibi/nightmare/ranWuZhe.png",
		"image/character/chibi/nightmare/shenGuan.png",
		"image/character/chibi/nightmare/shenJianShou.png",
		"image/character/chibi/nightmare/shenMiXueZhe.png",
		"image/character/chibi/nightmare/shengDianQiShi.png",
		"image/character/chibi/nightmare/shengGong.png",
		"image/character/chibi/nightmare/shengNv.png",
		"image/character/chibi/nightmare/shengQiangQiShi.png",
		"image/character/chibi/nightmare/shengTingJianChaShi.png",
		"image/character/chibi/nightmare/sheng_zhongCaiZhe.png",
		"image/character/chibi/nightmare/shiShenZhe.png",
		"image/character/chibi/nightmare/shouLingWuShi.png",
		"image/character/chibi/nightmare/tanLanShaoNv.png",
		"image/character/chibi/nightmare/tianShi.png",
		"image/character/chibi/nightmare/wenYiFaShi.png",
		"image/character/chibi/nightmare/xianZhe.png",
		"image/character/chibi/nightmare/xingZhuiNvWu.png",
		"image/character/chibi/nightmare/xueSeJianLing.png",
		"image/character/chibi/nightmare/xueZhiWuNv.png",
		"image/character/chibi/nightmare/yiJiaoTu.png",
		"image/character/chibi/nightmare/yinYangShi.png",
		"image/character/chibi/nightmare/yinYouShiRen.png",
		"image/character/chibi/nightmare/yingLingRenXing.png",
		"image/character/chibi/nightmare/yongZhe.png",
		"image/character/chibi/nightmare/youJiShi.png",
		"image/character/chibi/nightmare/yuanChuZhiGong.png",
		"image/character/chibi/nightmare/yuanSuShi.png",
		"image/character/chibi/nightmare/yueTuanShouXi.png",
		"image/character/chibi/nightmare/yueZhiNvShen.png",
		"image/character/chibi/nightmare/zhanDouFaShi.png",
		"image/character/chibi/nightmare/zhongCaiZhe.png",
		"image/character/chibi/nightmare/zhouFuShi.png",
		"image/character/chibi/nightmare/zhuLvZhe.png"
	],
	size: "189.87MB"
};

extension["宿命挽歌"] = {
	date: "2026/08/25",
	intro: "添加角色赵灵儿、李逍遥、林月如、阿奴、拜月教主及其水魔兽转化形态。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "1.8",
	files: ["info.json", "README.md", "LICENSE", "package.js", "zhaoLingEr.jpg", "liXiaoYao.jpg", "linYueRu.jpg", "aNu.jpg", "baiYueJiaoZhu.png", "shuiMoShouBaiYueJiaoZhu.png", "mark_lingLi.png", "mark_jianY.png", "mark_qiJing.png", "mark_gu.png", "mark_wuDuZhu.png", "mark_fengMo.png", "mark_hongShui.png", "audio/bgm/taoHuaHuanMeng.mp3", "audio/bgm/qingYuan.mp3", "audio/bgm/yuJianFuMo.mp3", "audio/bgm/niTianErXing.mp3", "audio/bgm/niTianErXing2.mp3", "audio/bgm/biWuZhaoQin.mp3", "audio/bgm/yunGuHeFeng.mp3", "audio/bgm/ending.mp3", "audio/bgm/dateALive.mp3", "audio/bgm/fengYiYangDeYongShi.mp3", "audio/bgm/swordland.mp3", "audio/bgm/gangGangJiJi.mp3", "audio/bgm/douPoCangQiong.mp3", "audio/bgm/pigstep.mp3"],
	size: "50.69MB"
};

extension["峡谷幻音"] = {
	date: "2026/08/25",
	intro: "添加角色提莫、亚托克斯。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "1.5",
	files: ["info.json", "README.md", "LICENSE", "package.js", "tiMo.jpg", "yaTuoKeSi.jpg", "mark_tiMoZhongMoGuKa.png", "mark_xueRen.png", "mark_xueJi.png", "mark_eHuoShuLianKa.png"],
	size: "965KB"
};

extension["永夜残响"] = {
	date: "2026/08/25",
	intro: "添加角色五河琴里、夜刀神十香、四糸乃、时崎狂三。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "1.4",
	files: ["info.json", "README.md", "LICENSE", "package.js", "wHeQingLi.jpg", "shiXiang.jpg", "siMiNai.jpg", "shiQiKuangSan.jpg", "mark_qinLiLingLi.png", "mark_shiXiangLingLi.png", "mark_siMiNaiBingJing.png", "mark_siMiNaiDongJie.png", "mark_shiCha.png", "mark_shiJianJingZhi.png"],
	size: "1.76MB"
};

extension["bigcowcow"] = {
	date: "2026/08/25",
	intro: "添加角色优菈、赫克托、史蒂夫、桐谷和人、一姬、萧炎。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "2.7",
	files: ["info.json", "README.md", "LICENSE", "package.js", "youLa.png", "huiFengQiangShi.png", "steve.png", "tongGuHeRen.png", "yiJi.png", "xiaoYan.png", "mark_fuChou.png", "mark_qiangShi.png", "mark_lianJi.png", "mark_miaoYun.png", "mark_douQi.png", "mark_anJin.png", "mark_qingLianDiXinHuo.png", "mark_yunLuoXinYan.png", "mark_guLingLengHuo.png", "mark_anDanQingLianDiXinHuo.png", "mark_anDanYunLuoXinYan.png", "mark_anDanGuLingLengHuo.png", "mark_jieShi.png"],
	size: "5.42MB"
};

extension["电啸龙吟"] = {
	date: "2026/08/25",
	intro: "添加角色奶龙、电棍Otto、永雏塔菲。",
	author: "蒙牛",
	netdisk: "",
	forum: "",
	version: "1.3",
	files: ["info.json", "README.md", "LICENSE", "package.js", "naiLong.jpg", "otto.jpg", "yongChuTaFei.jpg", "mark_hongWen.png", "mark_fangGuan.png", "mark_taFeiLiuLiang.png", "mark_gongJiReBang.png", "mark_faShuReBang.png", "mark_teShuReBang.png", "mark_taFeiShuTiao.png"],
	size: "1.09MB"
};
