if (!localStorage.getItem('old-extension-tip')) {
	alert('您在游戏内的扩展栏目获取的扩展可能导致游戏崩溃' +
		'，请谨慎下载');
	localStorage.setItem('old-extension-tip', 'true');
};

extension["织梦者"] = {
	date: "2025/05/12",
	intro: "玩弄技能的角色。游戏本体版本最低v1.0.2",
	author: "农之",
	netdisk: "",
	forum: "",
	version: "1.5",
	files: ["info.json", "LICENSE", "mengJingSuXing.jpg", "package.js", "README.md", "zhiMengZhe.jpg"],
	size: "1.8MB"
};

extension["无名杯UI优化包"] = {
	"date": "2026/09/18",
	"intro": "优化无名杯对局UI：重绘战况面板视觉，统一角色框、行动按钮、技能栏、卡牌、弹窗与日志的美术语言。",
	"author": "蒙牛 / Codex",
	"netdisk": "",
	"forum": "",
	"version": "2.3",
	"files": [
		"README.md",
		"extension.css",
		"extension.js",
		"image/baoShi_xianxia.png",
		"image/card/anMie_xianxia.png",
		"image/card/diLieZhan_xianxia.png",
		"image/card/fengShenZhan_xianxia.png",
		"image/card/huoYanZhan_xianxia.png",
		"image/card/leiGuangZhan_xianxia.png",
		"image/card/moDan_xianxia.png",
		"image/card/moRen_xianxia.png",
		"image/card/shengDun_xianxia.png",
		"image/card/shengGuang_xianxia.png",
		"image/card/shuiLianZhan_xianxia.png",
		"image/card/xuRuo_xianxia.png",
		"image/card/yiRen_xianxia.png",
		"image/card/zhongDu_xianxia.png",
		"image/cardback_xianxia.png",
		"image/huangDeng_xianxia.png",
		"image/lanDeng_xianxia.png",
		"image/shuiJing_xianxia.png",
		"image/waterbear/frame_huan_v2.png",
		"image/waterbear/frame_ji_v2.png",
		"image/waterbear/frame_sheng_v2.png",
		"image/waterbear/frame_xue_v2.png",
		"image/waterbear/frame_yong_v2.png",
		"image/waterbear/parchment_border.png",
		"image/waterbear/parchment_tile.png",
		"image/waterbear/table_wood.png",
		"image/xingJi_xianxia.png",
		"image/zhiLiaoCao_xianxia.png",
		"image/zhiLiao_xianxia.png",
		"info.json",
		"package.js",
		"waterbear.css"
	],
	"size": "25.75MB"
};

extension["十周年语音包"] = {
	"date": "2026/09/18",
	"intro": "十周年角色技能语音扩展。当前收录风之剑圣、狂战士、神箭手、封印师、暗杀者、圣女、守护天使、魔法少女、魔剑士、圣枪骑士、元素师、冒险家、瘟疫法师、仲裁者、神官、祈祷师、贤者、灵符师、格斗家、剑帝、灵魂术士、勇者、血之巫女、蝶舞者、女武神、魔弓、红莲骑士、英灵人形、魔枪、吟游诗人、苍炎魔女、精灵射手、血色剑灵、阴阳师、月之女神、兽灵武士、圣殿骑士、圣庭检察士、圣弓、原初之弓、星坠女巫、战斗法师、猎巫人、女仆长、矜贵之女、染污者、噬神者、结界师、红衣主教、铸律者、游击士、节日魔导、贪婪少女、见习制片、咒符师、怠惰少女与剑之子的全部技能语音。",
	"author": "蒙牛 / Codex",
	"netdisk": "",
	"forum": "",
	"version": "6.12",
	"files": [
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-07820a42441adb5a115841c4011d5760581218416aeea438bfcb4942d285fef4.json",
		"audio-data/pack-0ea2475ed754ada7c77a5b21e23a3a174bdb43cb09b9c4061aa7d3c8a9d54567.json",
		"audio-data/pack-19be6558d551a8e8984dac204a8d434ff31bb62bdcc6cc1f50e9f897e6eda2e6.json",
		"audio-data/pack-3a370c3ab686dfb7b885285c47ab61595da674755cc21a9586ce869295b07040.json",
		"audio-data/pack-474801ac273e8a7922e89f252f24975e4cab8087cc2fb73fd221500f2e0849c8.json",
		"audio-data/pack-5061f2c8ccaea1eed6a3c3e3a6dd4444250b4ae3d48012fc1d0930d4cd6c9ea5.json",
		"audio-data/pack-5ab844ae4cd8e3a53c538e388c2bed7590c8ec75fb24082e989fd69a3fff72f6.json",
		"audio-data/pack-d91914a1deeccc76f2677e0f95e7228b793789ae24c85e231962878030f0c569.json",
		"audio-data/pack-e4f8c096775ed02e76410c0a7b8b4a92eed7798fa5d3462ab94e6a9445065a05.json",
		"audio-data/pack-f8a99e289173ae10157b266580588a210116174233133f32fcfff418bca6a9ca.json",
		"audio-data/pack-fa413680958e3b039d684a42ec933c8cbc452a50de5a8ef3252d8b41350279b6.json",
		"audio/action/README.md",
		"extension.js",
		"info.json",
		"package.js"
	],
	"size": "50.66MB"
};

extension["创世纪"] = {
	"date": "2026/09/18",
	"intro": "添加角色贝亚娜斗神、百花缭乱、露米娅、天启者、狱血魔神。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "2.8",
	"files": [
		"LICENSE",
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-2fe13fb69036b592929995ad35f78b87a184b901452bd1aa877d25b7377d9864.json",
		"baiHuaLiaoLuan.png",
		"beiyanadopushen.png",
		"extension.js",
		"info.json",
		"luMiYa.png",
		"mark_huaShi.png",
		"mark_luMiYaYanJiu.png",
		"mark_nianQi.png",
		"mark_rongYuZhuFu.png",
		"mark_shouHuHuiZhang.png",
		"mark_tianQiZhiZhu.png",
		"mark_tianShiZhuFu.png",
		"mark_wuQiZhuFu.png",
		"mark_xueQi.png",
		"mark_xueShaXingTai.png",
		"package.js",
		"tianQiZhe.png",
		"yuXueMoShen.png"
	],
	"size": "9.70MB"
};

extension["十周年-AI优化版"] = {
	"date": "2026/09/16",
	"intro": "在不修改原版十周年角色技能与数值的前提下，优化购买、合成、技能发动、目标选择和资源保留等AI决策。",
	"author": "蒙牛 / Codex",
	"netdisk": "",
	"forum": "",
	"version": "1.7",
	"files": [
		"README.md",
		"extension.js",
		"info.json",
		"package.js"
	],
	"size": "0.45MB"
};

extension["十周年-噩梦人机"] = {
	"date": "2026/09/18",
	"intro": "内置十周年-AI优化版，为70名电脑角色提供140项噩梦强化技能；新增最多三名玩家的联机合作 PvE 模式。真人操控角色保持原版技能。",
	"author": "蒙牛 / Codex",
	"netdisk": "",
	"forum": "",
	"version": "1.9",
	"files": [
		"README.md",
		"extension.js",
		"image/character/chibi/default/anShaZhe.png",
		"image/character/chibi/default/cangYanMoNv.png",
		"image/character/chibi/default/chuanJiaoShi.png",
		"image/character/chibi/default/daiDuoShaoNv.png",
		"image/character/chibi/default/daoDanLuoLi.png",
		"image/character/chibi/default/dieWuZhe.png",
		"image/character/chibi/default/fengYinShi.png",
		"image/character/chibi/default/fengZhiJianSheng.png",
		"image/character/chibi/default/geDouJia.png",
		"image/character/chibi/default/hongLianQiShi.png",
		"image/character/chibi/default/hongYiZhuJiao.png",
		"image/character/chibi/default/jiDuShaoNv.png",
		"image/character/chibi/default/jiLuZhe.png",
		"image/character/chibi/default/jianDi.png",
		"image/character/chibi/default/jianXiZhiPian.png",
		"image/character/chibi/default/jianZhiMoNv.png",
		"image/character/chibi/default/jianZhiZi.png",
		"image/character/chibi/default/jieJieShi.png",
		"image/character/chibi/default/jieRiMoDao.png",
		"image/character/chibi/default/jinGuiZhiNv.png",
		"image/character/chibi/default/jingLingSheShou.png",
		"image/character/chibi/default/kuangZhanShi.png",
		"image/character/chibi/default/lieWuRen.png",
		"image/character/chibi/default/lingFuShi.png",
		"image/character/chibi/default/lingHunShuShi.png",
		"image/character/chibi/default/lingXiZhiChao.png",
		"image/character/chibi/default/luoLiFanZhang.png",
		"image/character/chibi/default/maoXianJia.png",
		"image/character/chibi/default/moFaShaoNv.png",
		"image/character/chibi/default/moGong.png",
		"image/character/chibi/default/moGongEX.png",
		"image/character/chibi/default/moJianShi.png",
		"image/character/chibi/default/moQiang.png",
		"image/character/chibi/default/nong_baoShiShaoNv.png",
		"image/character/chibi/default/nvPuZhang.png",
		"image/character/chibi/default/nvWuShen.png",
		"image/character/chibi/default/qiDaoShi.png",
		"image/character/chibi/default/ranWuZhe.png",
		"image/character/chibi/default/shenGuan.png",
		"image/character/chibi/default/shenJianShou.png",
		"image/character/chibi/default/shenMiXueZhe.png",
		"image/character/chibi/default/shengDianQiShi.png",
		"image/character/chibi/default/shengGong.png",
		"image/character/chibi/default/shengNv.png",
		"image/character/chibi/default/shengQiangQiShi.png",
		"image/character/chibi/default/shengTingJianChaShi.png",
		"image/character/chibi/default/sheng_zhongCaiZhe.png",
		"image/character/chibi/default/shiShenZhe.png",
		"image/character/chibi/default/shouLingWuShi.png",
		"image/character/chibi/default/tanLanShaoNv.png",
		"image/character/chibi/default/tianShi.png",
		"image/character/chibi/default/wenYiFaShi.png",
		"image/character/chibi/default/xianZhe.png",
		"image/character/chibi/default/xingZhuiNvWu.png",
		"image/character/chibi/default/xueSeJianLing.png",
		"image/character/chibi/default/xueZhiWuNv.png",
		"image/character/chibi/default/yiJiaoTu.png",
		"image/character/chibi/default/yinYangShi.png",
		"image/character/chibi/default/yinYouShiRen.png",
		"image/character/chibi/default/yingLingRenXing.png",
		"image/character/chibi/default/yongZhe.png",
		"image/character/chibi/default/youJiShi.png",
		"image/character/chibi/default/yuanChuZhiGong.png",
		"image/character/chibi/default/yuanSuShi.png",
		"image/character/chibi/default/yueTuanShouXi.png",
		"image/character/chibi/default/yueZhiNvShen.png",
		"image/character/chibi/default/zhanDouFaShi.png",
		"image/character/chibi/default/zhongCaiZhe.png",
		"image/character/chibi/default/zhouFuShi.png",
		"image/character/chibi/default/zhuLvZhe.png",
		"image/character/chibi/nightmare/anShaZhe.png",
		"image/character/chibi/nightmare/cangYanMoNv.png",
		"image/character/chibi/nightmare/chuanJiaoShi.png",
		"image/character/chibi/nightmare/daiDuoShaoNv.png",
		"image/character/chibi/nightmare/daoDanLuoLi.png",
		"image/character/chibi/nightmare/dieWuZhe.png",
		"image/character/chibi/nightmare/fengYinShi.png",
		"image/character/chibi/nightmare/fengZhiJianSheng.png",
		"image/character/chibi/nightmare/geDouJia.png",
		"image/character/chibi/nightmare/hongLianQiShi.png",
		"image/character/chibi/nightmare/hongYiZhuJiao.png",
		"image/character/chibi/nightmare/jiDuShaoNv.png",
		"image/character/chibi/nightmare/jiLuZhe.png",
		"image/character/chibi/nightmare/jianDi.png",
		"image/character/chibi/nightmare/jianXiZhiPian.png",
		"image/character/chibi/nightmare/jianZhiMoNv.png",
		"image/character/chibi/nightmare/jianZhiZi.png",
		"image/character/chibi/nightmare/jieJieShi.png",
		"image/character/chibi/nightmare/jieRiMoDao.png",
		"image/character/chibi/nightmare/jinGuiZhiNv.png",
		"image/character/chibi/nightmare/jingLingSheShou.png",
		"image/character/chibi/nightmare/kuangZhanShi.png",
		"image/character/chibi/nightmare/lieWuRen.png",
		"image/character/chibi/nightmare/lingFuShi.png",
		"image/character/chibi/nightmare/lingHunShuShi.png",
		"image/character/chibi/nightmare/lingXiZhiChao.png",
		"image/character/chibi/nightmare/luoLiFanZhang.png",
		"image/character/chibi/nightmare/maoXianJia.png",
		"image/character/chibi/nightmare/moFaShaoNv.png",
		"image/character/chibi/nightmare/moGong.png",
		"image/character/chibi/nightmare/moGongEX.png",
		"image/character/chibi/nightmare/moJianShi.png",
		"image/character/chibi/nightmare/moQiang.png",
		"image/character/chibi/nightmare/nong_baoShiShaoNv.png",
		"image/character/chibi/nightmare/nvPuZhang.png",
		"image/character/chibi/nightmare/nvWuShen.png",
		"image/character/chibi/nightmare/qiDaoShi.png",
		"image/character/chibi/nightmare/ranWuZhe.png",
		"image/character/chibi/nightmare/shenGuan.png",
		"image/character/chibi/nightmare/shenJianShou.png",
		"image/character/chibi/nightmare/shenMiXueZhe.png",
		"image/character/chibi/nightmare/shengDianQiShi.png",
		"image/character/chibi/nightmare/shengGong.png",
		"image/character/chibi/nightmare/shengNv.png",
		"image/character/chibi/nightmare/shengQiangQiShi.png",
		"image/character/chibi/nightmare/shengTingJianChaShi.png",
		"image/character/chibi/nightmare/sheng_zhongCaiZhe.png",
		"image/character/chibi/nightmare/shiShenZhe.png",
		"image/character/chibi/nightmare/shouLingWuShi.png",
		"image/character/chibi/nightmare/tanLanShaoNv.png",
		"image/character/chibi/nightmare/tianShi.png",
		"image/character/chibi/nightmare/wenYiFaShi.png",
		"image/character/chibi/nightmare/xianZhe.png",
		"image/character/chibi/nightmare/xingZhuiNvWu.png",
		"image/character/chibi/nightmare/xueSeJianLing.png",
		"image/character/chibi/nightmare/xueZhiWuNv.png",
		"image/character/chibi/nightmare/yiJiaoTu.png",
		"image/character/chibi/nightmare/yinYangShi.png",
		"image/character/chibi/nightmare/yinYouShiRen.png",
		"image/character/chibi/nightmare/yingLingRenXing.png",
		"image/character/chibi/nightmare/yongZhe.png",
		"image/character/chibi/nightmare/youJiShi.png",
		"image/character/chibi/nightmare/yuanChuZhiGong.png",
		"image/character/chibi/nightmare/yuanSuShi.png",
		"image/character/chibi/nightmare/yueTuanShouXi.png",
		"image/character/chibi/nightmare/yueZhiNvShen.png",
		"image/character/chibi/nightmare/zhanDouFaShi.png",
		"image/character/chibi/nightmare/zhongCaiZhe.png",
		"image/character/chibi/nightmare/zhouFuShi.png",
		"image/character/chibi/nightmare/zhuLvZhe.png",
		"image/character/default/anShaZhe.png",
		"image/character/default/cangYanMoNv.png",
		"image/character/default/chuanJiaoShi.png",
		"image/character/default/daiDuoShaoNv.png",
		"image/character/default/daoDanLuoLi.png",
		"image/character/default/dieWuZhe.png",
		"image/character/default/fengYinShi.png",
		"image/character/default/fengZhiJianSheng.png",
		"image/character/default/geDouJia.png",
		"image/character/default/hongLianQiShi.png",
		"image/character/default/hongYiZhuJiao.png",
		"image/character/default/jiDuShaoNv.png",
		"image/character/default/jiLuZhe.png",
		"image/character/default/jianDi.png",
		"image/character/default/jianXiZhiPian.png",
		"image/character/default/jianZhiMoNv.png",
		"image/character/default/jianZhiZi.png",
		"image/character/default/jieJieShi.png",
		"image/character/default/jieRiMoDao.png",
		"image/character/default/jinGuiZhiNv.png",
		"image/character/default/jingLingSheShou.png",
		"image/character/default/kuangZhanShi.png",
		"image/character/default/lieWuRen.png",
		"image/character/default/lingFuShi.png",
		"image/character/default/lingHunShuShi.png",
		"image/character/default/lingXiZhiChao.png",
		"image/character/default/luoLiFanZhang.png",
		"image/character/default/maoXianJia.png",
		"image/character/default/moFaShaoNv.png",
		"image/character/default/moGong.png",
		"image/character/default/moGongEX.png",
		"image/character/default/moJianShi.png",
		"image/character/default/moQiang.png",
		"image/character/default/nong_baoShiShaoNv.png",
		"image/character/default/nvPuZhang.png",
		"image/character/default/nvWuShen.png",
		"image/character/default/qiDaoShi.png",
		"image/character/default/ranWuZhe.png",
		"image/character/default/shenGuan.png",
		"image/character/default/shenJianShou.png",
		"image/character/default/shenMiXueZhe.png",
		"image/character/default/shengDianQiShi.png",
		"image/character/default/shengGong.png",
		"image/character/default/shengNv.png",
		"image/character/default/shengQiangQiShi.png",
		"image/character/default/shengTingJianChaShi.png",
		"image/character/default/sheng_zhongCaiZhe.png",
		"image/character/default/shiShenZhe.png",
		"image/character/default/shouLingWuShi.png",
		"image/character/default/tanLanShaoNv.png",
		"image/character/default/tianShi.png",
		"image/character/default/wenYiFaShi.png",
		"image/character/default/xianZhe.png",
		"image/character/default/xingZhuiNvWu.png",
		"image/character/default/xueSeJianLing.png",
		"image/character/default/xueZhiWuNv.png",
		"image/character/default/yiJiaoTu.png",
		"image/character/default/yinYangShi.png",
		"image/character/default/yinYouShiRen.png",
		"image/character/default/yingLingRenXing.png",
		"image/character/default/yongZhe.png",
		"image/character/default/youJiShi.png",
		"image/character/default/yuanChuZhiGong.png",
		"image/character/default/yuanSuShi.png",
		"image/character/default/yueTuanShouXi.png",
		"image/character/default/yueZhiNvShen.png",
		"image/character/default/zhanDouFaShi.png",
		"image/character/default/zhongCaiZhe.png",
		"image/character/default/zhouFuShi.png",
		"image/character/default/zhuLvZhe.png",
		"image/character/nightmare/anShaZhe.png",
		"image/character/nightmare/cangYanMoNv.png",
		"image/character/nightmare/chuanJiaoShi.png",
		"image/character/nightmare/daiDuoShaoNv.png",
		"image/character/nightmare/daoDanLuoLi.png",
		"image/character/nightmare/dieWuZhe.png",
		"image/character/nightmare/fengYinShi.png",
		"image/character/nightmare/fengZhiJianSheng.png",
		"image/character/nightmare/geDouJia.png",
		"image/character/nightmare/hongLianQiShi.png",
		"image/character/nightmare/hongYiZhuJiao.png",
		"image/character/nightmare/jiDuShaoNv.png",
		"image/character/nightmare/jiLuZhe.png",
		"image/character/nightmare/jianDi.png",
		"image/character/nightmare/jianXiZhiPian.png",
		"image/character/nightmare/jianZhiMoNv.png",
		"image/character/nightmare/jianZhiZi.png",
		"image/character/nightmare/jieJieShi.png",
		"image/character/nightmare/jieRiMoDao.png",
		"image/character/nightmare/jinGuiZhiNv.png",
		"image/character/nightmare/jingLingSheShou.png",
		"image/character/nightmare/kuangZhanShi.png",
		"image/character/nightmare/lieWuRen.png",
		"image/character/nightmare/lingFuShi.png",
		"image/character/nightmare/lingHunShuShi.png",
		"image/character/nightmare/lingXiZhiChao.png",
		"image/character/nightmare/luoLiFanZhang.png",
		"image/character/nightmare/maoXianJia.png",
		"image/character/nightmare/moFaShaoNv.png",
		"image/character/nightmare/moGong.png",
		"image/character/nightmare/moGongEX.png",
		"image/character/nightmare/moJianShi.png",
		"image/character/nightmare/moQiang.png",
		"image/character/nightmare/nong_baoShiShaoNv.png",
		"image/character/nightmare/nvPuZhang.png",
		"image/character/nightmare/nvWuShen.png",
		"image/character/nightmare/qiDaoShi.png",
		"image/character/nightmare/ranWuZhe.png",
		"image/character/nightmare/shenGuan.png",
		"image/character/nightmare/shenJianShou.png",
		"image/character/nightmare/shenMiXueZhe.png",
		"image/character/nightmare/shengDianQiShi.png",
		"image/character/nightmare/shengGong.png",
		"image/character/nightmare/shengNv.png",
		"image/character/nightmare/shengQiangQiShi.png",
		"image/character/nightmare/shengTingJianChaShi.png",
		"image/character/nightmare/sheng_zhongCaiZhe.png",
		"image/character/nightmare/shiShenZhe.png",
		"image/character/nightmare/shouLingWuShi.png",
		"image/character/nightmare/tanLanShaoNv.png",
		"image/character/nightmare/tianShi.png",
		"image/character/nightmare/wenYiFaShi.png",
		"image/character/nightmare/xianZhe.png",
		"image/character/nightmare/xingZhuiNvWu.png",
		"image/character/nightmare/xueSeJianLing.png",
		"image/character/nightmare/xueZhiWuNv.png",
		"image/character/nightmare/yiJiaoTu.png",
		"image/character/nightmare/yinYangShi.png",
		"image/character/nightmare/yinYouShiRen.png",
		"image/character/nightmare/yingLingRenXing.png",
		"image/character/nightmare/yongZhe.png",
		"image/character/nightmare/youJiShi.png",
		"image/character/nightmare/yuanChuZhiGong.png",
		"image/character/nightmare/yuanSuShi.png",
		"image/character/nightmare/yueTuanShouXi.png",
		"image/character/nightmare/yueZhiNvShen.png",
		"image/character/nightmare/zhanDouFaShi.png",
		"image/character/nightmare/zhongCaiZhe.png",
		"image/character/nightmare/zhouFuShi.png",
		"image/character/nightmare/zhuLvZhe.png",
		"image/splash/xieLing.png",
		"info.json",
		"package.js"
	],
	"size": "185.50MB"
};

extension["宿命挽歌"] = {
	"date": "2026/09/18",
	"intro": "添加角色赵灵儿、李逍遥、林月如、阿奴、拜月教主、鬼将军、蛇妖男、狐妖女及不可选的水魔兽、僵尸转化形态。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "2.32",
	"files": [
		"LICENSE",
		"README.md",
		"aNu.jpg",
		"audio-data/manifest.json",
		"audio-data/pack-171b2598f6208c7db0cd3bea4b790b6b6b0a309b74111a4185eb79edd44770d2.json",
		"audio-data/pack-1d8c5701617c9f8188e9809d8c8a68ac6da21612f7a5ed51657aa8cdc2262f56.json",
		"audio-data/pack-2690086030df5f78603076bb51022450080ebf42f1789c3c2607b040317c7e66.json",
		"audio-data/pack-28208b090295985624e6b4216a08bb2b476b7de052f4be6b3383f440c1290fa2.json",
		"audio-data/pack-53cd3739fe97529fdad9a0a7a04feea520081d6bc8f60005a1368a1dd9a37d7b.json",
		"audio-data/pack-56f7559a8ca6b52576d7924750d93f46b249a5dc4c35751061cc85a0e737acb3.json",
		"audio-data/pack-704879d868ad8db8f108bd21b54c3dfb5d51f303f2ba3148c4343e03aca9f8f4.json",
		"audio-data/pack-8421aa26366ec5f77619b9e886ca418b982e5409fa6248b01c1f423f79e52092.json",
		"audio-data/pack-86239e6e765377689b4cff97b65797175b02be8bf8c427724848f6f58738c771.json",
		"audio-data/pack-a025a8b5241d830a76753c33e33548d2131e3dea4a387eb33d2dfe26a06ce6ed.json",
		"audio-data/pack-a157e8a9d21889948ea1f9d053e2e92532b283f468dd699fdfff7d36415a94be.json",
		"audio-data/pack-a26dbda2ff11a1eced2057e93bb69d0d16849c32dfb351d418de6785a896bcb3.json",
		"audio-data/pack-adcaf49932a72bbb9eb8acf900de81d15ef111d9b3557b3592680029319dffad.json",
		"audio-data/pack-e582dfa0be89841445adb41228be58764bdd379db40fccf3212210163d0205d9.json",
		"audio-data/pack-f920a3d4b2490186ec0bd8915271e4eae81857c44a55af233221fdbbdd520af1.json",
		"baiYueJiaoZhu.png",
		"extension.js",
		"guiJiangJun.png",
		"huYaoNv.png",
		"info.json",
		"liXiaoYao.jpg",
		"linYueRu.jpg",
		"mark_fengMo.png",
		"mark_gu.png",
		"mark_hongShui.png",
		"mark_jianY.png",
		"mark_jueXingDu.png",
		"mark_lingLi.png",
		"mark_qiJing.png",
		"mark_shiDu.png",
		"mark_wuDuZhu.png",
		"mark_yinQi.png",
		"package.js",
		"sheYaoNan.png",
		"shuiMoShouBaiYueJiaoZhu.png",
		"suMingJiangShi.png",
		"zhaoLingEr.jpg",
		"zhaoLingEr_mengShe.png"
	],
	"size": "79.27MB"
};

extension["峡谷幻音"] = {
	"date": "2026/09/18",
	"intro": "添加角色提莫、娑娜、亚托克斯、巴德。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "1.13",
	"files": [
		"LICENSE",
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-5e86f3ff06b64ea1dcdb5f4edfe74eb630715d1adb0230a617a4e47b9d4de694.json",
		"baDe.jpg",
		"extension.js",
		"info.json",
		"mark_baDeChiHuan.png",
		"mark_baDeMuLing.png",
		"mark_baDeNingZhi.png",
		"mark_baDeShenQiLvCheng.png",
		"mark_baDeTiaoHeZhiYin.png",
		"mark_baDeYouShenShengTan.png",
		"mark_eHuoShuLianKa.png",
		"mark_suoNaHeXian.png",
		"mark_suoNaJianYiYuYin.png",
		"mark_suoNaXunJieYuYin.png",
		"mark_suoNaYingYongYuYin.png",
		"mark_tiMoZhongMoGuKa.png",
		"mark_xueJi.png",
		"mark_xueRen.png",
		"package.js",
		"suoNa.jpg",
		"tiMo.jpg",
		"yaTuoKeSi.jpg"
	],
	"size": "5.26MB"
};

extension["永夜残响"] = {
	"date": "2026/09/18",
	"intro": "添加角色五河琴里、夜刀神十香、四糸乃、时崎狂三、鸢一折纸；含隐藏反转形态。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "2.6",
	"files": [
		"LICENSE",
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-fe863965b566d7c7ada0819d639f9386b79cd365728766f25ae04d2d50dbe7ef.json",
		"extension.js",
		"fanZhuanShiXiang.png",
		"fanZhuanZheZhi.png",
		"info.json",
		"mark_fanZhuanLingLi.png",
		"mark_qinLiLingLi.png",
		"mark_shiCha.png",
		"mark_shiJianJingZhi.png",
		"mark_shiXiangLingLi.png",
		"mark_siMiNaiBingJing.png",
		"mark_siMiNaiDongJie.png",
		"mark_zheZhiGuangYu.png",
		"mark_zheZhiHeiYu.png",
		"package.js",
		"shiQiKuangSan.jpg",
		"shiXiang.jpg",
		"siMiNai.jpg",
		"wHeQingLi.jpg",
		"yuanYiZheZhi.png"
	],
	"size": "11.91MB"
};

extension["bigcowcow"] = {
	"date": "2026/09/18",
	"intro": "添加角色优菈、赫克托、史蒂夫、桐谷和人、一姬、萧炎。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "2.13",
	"files": [
		"LICENSE",
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-9b26aa933650ff7a667109d4b3b101b06fe242b878ebc546ae228f93cf51211f.json",
		"extension.js",
		"huiFengQiangShi.png",
		"info.json",
		"mark_anDanGuLingLengHuo.png",
		"mark_anDanQingLianDiXinHuo.png",
		"mark_anDanYunLuoXinYan.png",
		"mark_anJin.png",
		"mark_douQi.png",
		"mark_fuChou.png",
		"mark_guLingLengHuo.png",
		"mark_jieShi.png",
		"mark_lianJi.png",
		"mark_miaoYun.png",
		"mark_qiangShi.png",
		"mark_qingLianDiXinHuo.png",
		"mark_yunLuoXinYan.png",
		"package.js",
		"steve.png",
		"tongGuHeRen.png",
		"xiaoYan.png",
		"yiJi.png",
		"youLa.png"
	],
	"size": "9.60MB"
};

extension["电啸龙吟"] = {
	"date": "2026/09/18",
	"intro": "添加角色奶龙、电棍Otto、永雏塔菲。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "1.8",
	"files": [
		"LICENSE",
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-fe851f1e37c3475e02771544b880096fe46bcdbf9a8a08e777a6fe8fccb6762b.json",
		"extension.js",
		"info.json",
		"mark_faShuReBang.png",
		"mark_fangGuan.png",
		"mark_gongJiReBang.png",
		"mark_hongWen.png",
		"mark_taFeiLiuLiang.png",
		"mark_taFeiShuTiao.png",
		"mark_teShuReBang.png",
		"naiLong.jpg",
		"otto.jpg",
		"package.js",
		"yongChuTaFei.jpg"
	],
	"size": "3.05MB"
};


extension["轮回遗梦"] = {
	"date": "2026/09/18",
	"intro": "仙剑奇侠传三主题角色包：景天、雪见、龙葵、邪剑仙。",
	"author": "蒙牛",
	"netdisk": "",
	"forum": "",
	"version": "1.4",
	"files": [
		"README.md",
		"audio-data/manifest.json",
		"audio-data/pack-30d343f2bd7c72a5dad6ebdc4fa2b2711dc3cad896185d95831ef0b34eba3615.json",
		"audio-data/pack-39b2f1cdb28cd709ee80abce0d7e9536ebaa1b66cf6bd6cbfd7587067a030228.json",
		"audio-data/pack-ad8c71e8ff0da2e2b73f795cd960927be54aa47a4a25045b89841f67d6eeedb9.json",
		"audio-data/pack-df29f146515d0dbbd558861a1d169b8400b4f871be77be24bce01a94339f16d3.json",
		"audio-data/pack-eb995abacc83a06329a27fc38bdc2615572bf859f1de520e59541b8b650fbb8f.json",
		"audio-data/pack-f2285c99931ae310746b35a2f185f871c99f12823d5d148049ea78b953ee21aa.json",
		"extension.js",
		"info.json",
		"jingTian.svg",
		"jingTian_moJian.png",
		"jingTian_zhenYaoJian.png",
		"longKui_blue.png",
		"longKui_red.png",
		"mark_canYing.png",
		"mark_huaYing.png",
		"mark_jianHun.png",
		"mark_longJingShi.png",
		"mark_moJian.png",
		"mark_route_moJian.png",
		"mark_route_zhenYaoJian.png",
		"mark_wuLing_feng_both.png",
		"mark_wuLing_feng_empty.png",
		"mark_wuLing_feng_yang.png",
		"mark_wuLing_feng_yin.png",
		"mark_wuLing_huo_both.png",
		"mark_wuLing_huo_empty.png",
		"mark_wuLing_huo_yang.png",
		"mark_wuLing_huo_yin.png",
		"mark_wuLing_lei_both.png",
		"mark_wuLing_lei_empty.png",
		"mark_wuLing_lei_yang.png",
		"mark_wuLing_lei_yin.png",
		"mark_wuLing_shui_both.png",
		"mark_wuLing_shui_empty.png",
		"mark_wuLing_shui_yang.png",
		"mark_wuLing_shui_yin.png",
		"mark_wuLing_tu_both.png",
		"mark_wuLing_tu_empty.png",
		"mark_wuLing_tu_yang.png",
		"mark_wuLing_tu_yin.png",
		"mark_xieNian.png",
		"mark_zhenYaoJian.png",
		"package.js",
		"xieJianXian.png",
		"xieLing.png",
		"xueJian.png"
	],
	"size": "34.38MB"
};
