extension["噬神者"]={
	intro:"噬神者，游戏本体版本最低1.0.8",
	author:"农杰",
	netdisk:"",
	forum:"",
	version:"1.0",
	files:["info.json","LICENSE","moRenCard.jpg","README.md","shiShenZhe.jpg","yiRenCard.jpg"],
	size:"999KB"
};