extension["噬神者"]={
	intro:"噬神者，游戏本体版本最低1.0.8",
	author:"农杰",
	netdisk:"",
	forum:"",
	version:"1.3",
	files:["info.json","LICENSE","moRenCard.png","README.md","shiShenZhe.jpg","yiRenCard.png"],
	size:"999KB"
};