extension["破晓"]={
	intro:"星杯传说：破晓ver1.4。增加星杯传说破晓角色。bug反馈：aabbcczhy@163.com",
	author:"LerU",
	netdisk:"",
	forum:"",
	version:"1.4",
	files:["info.json","LICENSE","youXia.jpg","zhanXingJia.jpg","tianmaqishi.jpg","shengtangcike.jpg","dasiji.jpg","lianjinshushi.jpg","xuetianshi.jpg","xinlingsushi.jpg","zhenLongNvWang.jpg","longKuangMiSuo.jpg","longMaiShuFu.jpg","longYuFengYin.jpg","yuLongJieJie.jpg","baiWanLongYan.jpg","longWangZhiLi.jpg","longShenEnHui.jpg","jianwuzhe.jpg","caijuezhe.jpg","shuangxuegongzhu.jpg","shouwangzhe.jpg","wudoujia.jpg","shengLongWeiYa.jpg","package.js","README.md"],
	size:"6.81M"
};