extension["无名杯UI优化包"] = {
    intro: "优化无名杯对局UI：重绘战况面板视觉，统一角色框、行动按钮、技能栏、卡牌、弹窗与日志的美术语言。",
    author: "蒙牛 / Codex",
    netdisk: "",
    forum: "",
    version: "2.1",
    files: [
        "info.json",
        "README.md",
        "package.js",
        "extension.js",
        "extension.css",
        "waterbear.css",
        "image/waterbear/table_wood.png",
        "image/waterbear/parchment_tile.png",
        "image/waterbear/parchment_border.png",
        "image/waterbear/frame_xue_v2.png",
        "image/waterbear/frame_sheng_v2.png",
        "image/waterbear/frame_ji_v2.png",
        "image/waterbear/frame_huan_v2.png",
        "image/waterbear/frame_yong_v2.png",
        "image/shuiJing_xianxia.png",
        "image/baoShi_xianxia.png",
        "image/cardback_xianxia.png",
        "image/zhiLiaoCao_xianxia.png",
        "image/zhiLiao_xianxia.png",
        "image/huangDeng_xianxia.png",
        "image/lanDeng_xianxia.png",
        "image/xingJi_xianxia.png",
        "image/card/anMie_xianxia.png",
        "image/card/shuiLianZhan_xianxia.png",
        "image/card/huoYanZhan_xianxia.png",
        "image/card/fengShenZhan_xianxia.png",
        "image/card/leiGuangZhan_xianxia.png",
        "image/card/diLieZhan_xianxia.png",
        "image/card/shengGuang_xianxia.png",
        "image/card/shengDun_xianxia.png",
        "image/card/xuRuo_xianxia.png",
        "image/card/zhongDu_xianxia.png",
        "image/card/moDan_xianxia.png",
        "image/card/moRen_xianxia.png",
        "image/card/yiRen_xianxia.png"
    ],
    size: "25.2MB"
};
