extension["织梦者"]={
	intro:"玩弄技能的角色。游戏本体版本最低v1.0.2",
	author:"农之",
	netdisk:"",
	forum:"",
	version:"1.3",
	files:["info.json","LICENSE","mengJingSuXing.jpg","package.js","README.md","zhiMengZhe.jpg"],
	size:"1.8MB"
};