extension["峡谷幻音"]={
    intro:"添加角色提莫、亚托克斯。",
    author:"蒙牛",
    netdisk:"",
    forum:"",
    version:"1.5",
    files:[
    "info.json",
    "README.md",
    "LICENSE",
    "package.js",
    "extension.js",
    "tiMo.jpg",
    "yaTuoKeSi.jpg",
    "mark_tiMoZhongMoGuKa.png",
    "mark_xueRen.png",
    "mark_xueJi.png",
    "mark_eHuoShuLianKa.png"
],
    size:"2.13MB"
};
